import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Javascript Frameworks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload framework pages for faster navigation */}
        <link rel="prefetch" href="/react" />
        <link rel="prefetch" href="/vue" />
        <link rel="prefetch" href="/angular" />
        <link rel="prefetch" href="/nodejs" />
        <link rel="prefetch" href="/express" />
        <link rel="prefetch" href="/nextjs" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
